# all available options: https://goreleaser.com/customization/
project_name: jamal

builds:
- binary: jamal
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - windows
  - linux
  goarch:
  - amd64
  - arm64
  - arm
  goarm:
  - 6
  - 7
  ldflags: []

archive:
  name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
  format_overrides:
  - goos: windows
    format: zip
  - goos: darwin
    format: zip
  - goos: linux
    format: zip
